targets:
  $default:
    sources:
      - lib/**
      - pubspec.*
      - $package$
      - integration_test/**.dart
    builders:
      generators|annotations:
        enabled: true

builders:
  flucumber:
    target: ":flucumber"
    import: "package:flucumber/flucumber.dart"
    builder_factories: ["flucumberBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]