# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/flucumber" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "pub"
    directory: "/flucumber_annotations"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "pub"
    directory: "/flucumber_generator" # Location of package manifests
    schedule:
      interval: "weekly"
