include: package:lints/recommended.yaml

linter:
  rules:
    #Excluded
    avoid_relative_lib_imports: false
    implementation_imports: false
    depend_on_referenced_packages: false

    #Additionally included
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    cast_nullable_to_non_nullable: true
    combinators_ordering: true
    conditional_uri_does_not_exist: true
    directives_ordering: true
    enable_null_safety: true
    eol_at_end_of_file: true
    flutter_style_todos: true
    no_runtimeType_toString: true
    only_throw_errors: true
    package_api_docs: true
    prefer_asserts_with_message: true
    prefer_final_in_for_each: true
    type_annotate_public_apis: true
    use_string_buffers: true

dart_code_metrics:
  anti-patterns:
    - long-method:
  rules:
    - no-boolean-literal-compare
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-returning-widgets
    - newline-before-return
    - avoid-global-state
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions:
        acceptable-level: 1
    - no-boolean-literal-compare
    - no-object-declaration
    - prefer-commenting-analyzer-ignores
    - prefer-first
    - prefer-last
    - always-remove-listener
    - avoid-unnecessary-setstate
    - prefer-extracting-callbacks:
        ignored-named-arguments:
          - builder
        allowed-line-count: 5
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - provide-correct-intl-args
