name: flucumber

packages:
  - example/**
  - flucumber/**
  - flucumber_generator/**
  - flucumber_annotations/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  postbootstrap:
    run: melos run gen --no-select

  gen:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    description: Generate code for all modules
    select-package:
      depends-on:
        - build_runner