name: flucumber

packages:
  - example/**
  - flucumber/**
  - flucumber_generator/**
  - flucumber_annotations/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  gen:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    description: Generate code for all modules
    select-package:
      depends-on:
        - build_runner

  format:
    exec: dart format . --fix
    description: Format all files

  fix:
    exec: dart fix --apply
    description: Fix analysis issues where possible

  analyze:
    exec: dart analyze .
    description: Analyze all packages