targets:
  $default:
    sources:
      - lib/**
      - pubspec.*
      - $package$
      - integration_test/**.dart
    builders:
      generators|annotations:
        enabled: true

builders:
  flucumber_steps_generator:
    import: "package:flucumber_generator/flucumber_generator.dart"
    builder_factories: [ "flucumberStepsBuilder" ]
    build_extensions: { ".dart": [ ".flucumber.json" ] }
    auto_apply: dependents
    runs_before: [ "flucumber|flucumber" ]
    build_to: cache
  flucumber:
    import: "package:flucumber_generator/flucumber_generator.dart"
    builder_factories: [ "flucumberBuilder" ]
    build_extensions: { ".dart": [ ".flucumber.dart" ] }
    auto_apply: dependents
    build_to: source