targets:
  $default:
    sources:
      - lib/**
      - pubspec.*
      - $package$
      - integration_test/**.dart
    builders:
      generators|annotations:
        enabled: true

builders:
  flucumber:
    target: ":flucumber"
    import: "package:flucumber_generator/flucumber_generator.dart"
    builder_factories: ["flucumberBuilder"]
    build_extensions: { ".dart": [".flucumber.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]